### ISSUE TITLE
Support polkadot 0.9.20

### ISSUE THREAD

**Issue by NunoAlexandre** [centrifuge/fudge#29]
We started [upgrading to polkadot v0.9.20](https://github.com/centrifuge/fudge/tree/v0.9.20) which bumps into some issues with the deprecation of `RelayChainLocal`.

Work on supporting this new version and once that's done, follow up with https://github.com/centrifuge/centrifuge-chain/issues/819.

**Comment by mustermeiszer** [comment]
done
